# Generated by Django 4.1.8 on 2023-10-25 13:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='files/', verbose_name='Файл')),
                ('uploaded_at', models.DateTimeField(default=datetime.datetime.now, verbose_name='Дата загрузки')),
                ('processed', models.BooleanField(default=False, verbose_name='Обработан')),
            ],
        ),
    ]
